<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>6.1.2.0</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <OutputPath>bin\Debug</OutputPath>
    <LangVersion>default</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapr.Client" Version="1.15.4" />
    <PackageReference Include="IoTCenter.Extensions.Logging" Version="2.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SerialPortStream" Version="2.4.2" />
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.9" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <PropertyGroup>
    <Authors>shendong</Authors>
    <Company>ganweisoft</Company>
    <Copyright>深圳市敢为软件技术有限公司</Copyright>
    <BaseOutputPath>D:\IoTCenter-6.1\bin</BaseOutputPath>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>E:\IoTCenter-6.1\bin\</OutputPath>
  </PropertyGroup>
</Project>