name: TOMs Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  host-build:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with: 
        ref: main
        submodules: true
        sparse-checkout: |
          subrepos/GrpcServer

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Host Restore Dependencies
      run: dotnet restore ./subrepos/GrpcServer/src/IoTCenterHost.sln

    - name: Host Build
      run: dotnet build ./subrepos/GrpcServer/src/IoTCenterHost.sln --configuration Release --no-restore

    - name: Host Publish
      run: dotnet publish ./subrepos/GrpcServer/src/IoTCenterHost.sln --self-contained false --configuration Release --no-build --output ./release/bin

    - name: Data Publish
      run: |
        cd ./release
        Copy-Item -Path ../subrepos/GrpcServer/src/config/* -Destination ./ -Recurse -Force
        cd ..
      shell: pwsh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-host-${{ matrix.os }}
        path: ./release/*

  api-build:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with: 
        ref: main
        submodules: true
        sparse-checkout: |
          subrepos/WebPlugins/src/back-end

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: WebApi Restore Dependencies
      run: dotnet restore ./subrepos/WebPlugins/src/back-end/IoTCenterWebApi.sln

    - name: WebApi Build
      run: dotnet build ./subrepos/WebPlugins/src/back-end/IoTCenterWebApi/IoTCenterWebApi.csproj --configuration Release --no-restore

    - name: WebApi Publish
      run: dotnet publish ./subrepos/WebPlugins/src/back-end/IoTCenterWebApi/IoTCenterWebApi.csproj --self-contained false --configuration Release --no-build --output ./release/IoTCenterWeb/publish 

    - name: Plugins Build
      run: dotnet build ./subrepos/WebPlugins/src/back-end/IoTCenterWebApi.sln

    - name: Plugins Publish
      run: |        
        Copy-Item -Path ./subrepos/WebPlugins/src/back-end/plugins -Destination .release/IoTCenterWeb/publish/plugins -Recurse -Force
      shell: pwsh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-api-${{ matrix.os }}
        path: ./release/*

  release-upload :
    needs: [create-release,host-build,api-build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    
    - name: Download Host Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-host-${{ matrix.os }}
        path: ./

    - name: Download Api Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-api-${{ matrix.os }}
        path: ./

    - name: Zip Release      
      run: |
        Compress-Archive -Path * -DestinationPath ./release_${{ matrix.os }}.zip -Force        
      shell: pwsh

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./release_${{ matrix.os }}.zip
        asset_name: ${{ runner.os }}_${{ runner.arch }}_${{ github.ref_name }}_release.zip
        asset_content_type: application/zip
